[package]
name = "libcfd-rpc"
version = "0.2.0"
edition = "2024"

[dependencies]
capnp = "0.27"
futures-io = "0.3"
thiserror = "2"
tracing = "0.1"

[build-dependencies]
capnpc = "0.27"

[dev-dependencies]
futures = "0.3"
tokio = { version = "1", features = ["io-util", "rt", "rt-multi-thread", "macros", "net"] }
